#ifndef CGAL_ONCE
#define CGAL_ONCE
#pragma once
#include <pgl_functs.hpp>
using namespace std;
using namespace PGL;
typedef void (*CGAL_Test_PGL)CGAL_Test_PGL
typedef void (*CGAL_Vector_Base)CGAL_Vector_Base
typedef void (*CGAL_Export_Path_Segment)CGAL_Export_Path_Segment
typedef void (*CGAL_Export_Path_Point)CGAL_Export_Path_Point
typedef void (*CGAL_2D_Distance_Point_Point)CGAL_2D_Distance_Point_Point
typedef void (*CGAL_2D_Distance_Point_Line)CGAL_2D_Distance_Point_Line
typedef void (*CGAL_2D_Distance_Point_Segment)CGAL_2D_Distance_Point_Segment
typedef void (*CGAL_2D_Distance_Segment_Segment)CGAL_2D_Distance_Segment_Segment
typedef void (*CGAL_2D_Location_Point_Polygon)CGAL_2D_Location_Point_Polygon
typedef void (*CGAL_2D_Location_Points_Polygon)CGAL_2D_Location_Points_Polygon
typedef void (*CGAL_2D_Distance_Point_Polygon)CGAL_2D_Distance_Point_Polygon
typedef void (*CGAL_2D_Intersection_Segment_Segment)CGAL_2D_Intersection_Segment_Segment
typedef void (*CGAL_2D_Intersection_Line_Line)CGAL_2D_Intersection_Line_Line
typedef void (*CGAL_2D_Intersection_Segment_Polygon)CGAL_2D_Intersection_Segment_Polygon
typedef void (*CGAL_2D_Polygon_Is_Clockwise_Oriented)CGAL_2D_Polygon_Is_Clockwise_Oriented
typedef void (*CGAL_2D_Two_Polygons_Union)CGAL_2D_Two_Polygons_Union
typedef void (*CGAL_2D_Two_Polygons_Intersection)CGAL_2D_Two_Polygons_Intersection
typedef void (*CGAL_Decompose_Polyline)CGAL_Decompose_Polyline
typedef void (*CGAL_Identify_Polycut_Extend)CGAL_Identify_Polycut_Extend
typedef void (*CGAL_Identify_Polycut_NotExtend)CGAL_Identify_Polycut_NotExtend
typedef void (*CGAL_Identify_Polycut)CGAL_Identify_Polycut
typedef void (*CGAL_2D_Polygon_One_Offsets)CGAL_2D_Polygon_One_Offsets
typedef void (*CGAL_Construct_InOutSide_Polygon)CGAL_Construct_InOutSide_Polygon
typedef void (*CGAL_2D_Intersection_Ray_Segment)CGAL_2D_Intersection_Ray_Segment
typedef void (*CGAL_Get_Angle_Kerf_Offset_Tan)CGAL_Get_Angle_Kerf_Offset_Tan
typedef void (*CGAL_3D_Distance_Point_Segment)CGAL_3D_Distance_Point_Segment
typedef void (*CGAL_3D_Plane_Fitting)CGAL_3D_Plane_Fitting
typedef void (*CGAL_3D_Plane_Point_Projection)CGAL_3D_Plane_Point_Projection
typedef void (*CGAL_3D_Plane_Points_Projection)CGAL_3D_Plane_Points_Projection
typedef void (*CGAL_3D_Plane_3D_to_2D_Point)CGAL_3D_Plane_3D_to_2D_Point
typedef void (*CGAL_3D_Plane_2D_to_3D_Point)CGAL_3D_Plane_2D_to_3D_Point
typedef void (*CGAL_3D_Plane_3D_to_2D_Points)CGAL_3D_Plane_3D_to_2D_Points
typedef void (*CGAL_3D_Plane_2D_to_3D_Points)CGAL_3D_Plane_2D_to_3D_Points
typedef void (*CGAL_3D_Projection_Point_Segment)CGAL_3D_Projection_Point_Segment
typedef void (*CGAL_3D_Distance_Point_Point)CGAL_3D_Distance_Point_Point
typedef void (*CGAL_3D_Distance_Point_Polygon)CGAL_3D_Distance_Point_Polygon
typedef void (*CGAL_2D_Polygon_Triangulation)CGAL_2D_Polygon_Triangulation
typedef void (*CGAL_Remesh_Surface_by_Adding_Feature)CGAL_Remesh_Surface_by_Adding_Feature
typedef void (*CGAL_3D_Read_Triangle_Mesh)CGAL_3D_Read_Triangle_Mesh
typedef void (*CGAL_Mesh_Edges)CGAL_Mesh_Edges
typedef void (*CGAL_3D_Intersection_Sphere_Ray)CGAL_3D_Intersection_Sphere_Ray
typedef void (*CGAL_3D_Intersection_Ray_Triangle)CGAL_3D_Intersection_Ray_Triangle
typedef void (*CGAL_3D_Intersection_Ray_Mesh)CGAL_3D_Intersection_Ray_Mesh
typedef void (*CGAL_3D_Intersection_Rays_Mesh)CGAL_3D_Intersection_Rays_Mesh
#endif
